name: ros2-listener-dl-py
version: '2.2.0'
summary: ROS 2 listener stores a received ROS 2 message into a ctrlX Data Layer node
description: |
  A ROS 2 listener:
  Receives a ROS 2 message and writes it into the ctrlX Data Layer node
  ros2/listener-dl/cpu-utilisation-percent.

base: core22
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  # The `source` here is the tarred staging area of the ros-base snap.
  ros-app:
    plugin: dump
    source: install
    stage-packages: [libpython3.10]
    override-build: |   
        craftctl default

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run.sh : usr/bin/run

apps:
  publisher:
    command: usr/bin/run
    plugs:
      - ros-base
      - network
      - network-bind
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer        