name: ros2-simple-listener-dl-cpp
version: '2.4.0'
summary: Snap with simple ROS 2 listener
description: |
  A simple ROS 2 listener which receives ROS 2 messages on topic 'ros2_simple_cpp'.

base: core22
grade: stable
confinement: strict
type: app

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  ros-app:
    plugin: dump
    source: install
    stage-packages:
      - ctrlx-datalayer
    override-build: |
        craftctl default

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run-listener.sh : usr/bin/run-listener

apps:
  listener:
    command: usr/bin/run-listener
    plugs:
      - ros-base
      - network
      - network-bind
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
    
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer

lint:
  ignore:
    - library:
      - usr/lib/aarch64-linux-gnu/libcomm_datalayer.so.*
      - usr/lib/x86_64-linux-gnu/libcomm_datalayer.so.*    
