name: ros2-simple-talker-cpp
version: 3.1.0
summary: Snap with simple ROS 2 talker
description: |
  A simple ROS 2 talker publishes messages on topic 'ros2_simple_cpp'.

base: core24
grade: stable
confinement: strict
type: app

title: ROS2 Jazzy Simple Talker
contact: https://github.com/boschrexroth/ctrlx-automation-sdk-ros2
license: MIT
donation: https://github.com/boschrexroth/ctrlx-automation-sdk-ros2/donation
issues: https://github.com/boschrexroth/ctrlx-automation-sdk-ros2/issues
source-code: https://github.com/boschrexroth/ctrlx-automation-sdk-ros2
website: https://github.com/boschrexroth/ctrlx-automation-sdk-ros2

platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  ros-app:
    plugin: dump
    source: install

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run-talker.sh : usr/bin/run-talker

apps:
  talker:
    command: usr/bin/run-talker
    plugs:
      - ros-base
      - network
      - network-bind
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
