name: ros2-simple-talker-cpp
version: '2.2.0'
summary: Snap with simple ROS 2 talker
description: |
  A simple ROS 2 talker publishes messages on topic 'ros2_simple_cpp'.

base: core22
grade: stable
confinement: strict

parts:
  ros-app:
    plugin: dump
    source: install

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run-talker.sh : usr/bin/run-talker

apps:
  talker:
    command: usr/bin/run-talker
    plugs:
      - ros-base
      - network
      - network-bind
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
 