# This is a basic workflow to help you get started with Actions

name: Build Snap

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  SetupAndBuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
      - run: vcs --help
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo snap install snapcraft --channel=7.x/stable --classic
      - run: rosdep update
      - run: |
          cd simple-listener-py
          ./build-snap-amd64.sh
      - run: |
          cd simple-listener-cpp
          ./build-snap-amd64.sh
      - run: |
          cd simple-listener-dl-py
          ./build-snap-amd64.sh
      - run: |
          cd simple-talker-py
          ./build-snap-amd64.sh
      - run: |
          cd simple-talker-cpp
          ./build-snap-amd64.sh
      - run: |
          cd simple-talker-dl-py
          ./build-snap-amd64.sh
