# With this workflow, snaps are created from each example.

name: Build Snap

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  SetupAndBuild:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
          SNAPCRAFT_ENABLE_EXPERIMENTAL_TARGET_ARCH: 1
      - run: vcs --help

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install snapcraft
        run: sudo snap install snapcraft --channel=7.x/stable --classic

      - name: Update ROS development
        run: rosdep update

      - name: Set up Snapcraft env
        run: |
          echo "SNAPCRAFT_BUILD_ENVIRONMENT=host" >> "$GITHUB_ENV"
          echo "SNAPCRAFT_ENABLE_EXPERIMENTAL_TARGET_ARCH=1" >> "$GITHUB_ENV"

      - run: |
          cd simple-listener-py
          ./build-snap-amd64.sh
      - run: |
          cd simple-listener-cpp
          ./build-snap-amd64.sh
      - run: |
          cd simple-listener-dl-py
          ./build-snap-amd64.sh
      - run: |
          cd simple-talker-py
          ./build-snap-amd64.sh
      - run: |
          cd simple-talker-cpp
          ./build-snap-amd64.sh
      - run: |
          cd simple-talker-dl-py
          ./build-snap-amd64.sh
